### ISSUE TITLE
panic: interface conversion: *beegoormadapter.Adapter is not persist.Adapter: missing method LoadPolicy

### ISSUE THREAD

**Issue by MaksNech** [casbin/beego-orm-adapter#5]
I have problem when run my app I catch error: "panic: interface conversion: *beegoormadapter.Adapter is not persist.Adapter: missing method LoadPolicy
". 

My dependencies:
Go 1.14
github.com/casbin/beego-orm-adapter v0.0.0-20180421160615-ba104911ae5b
github.com/casbin/casbin/v2 v2.2.1

What problem is it?

**Comment by hsluoyz** [comment]
Transferred to: https://github.com/casbin/beego-orm-adapter/issues

**Comment by hsluoyz** [comment]
@MaksNech fixed in: https://github.com/casbin/beego-orm-adapter/pull/7

**Comment by MaksNech** [comment]
@hsluoyz @nodece  Hi collegues, the problem is still not resolved.
I created a new empty project to test the compatibility of work casbin v2 with beego-orm-adapter. When I set dependencies using Go modules I catch next error:

![Screen Shot 2020-03-20 at 1 42 47 PM](https://user-images.githubusercontent.com/29229656/77161344-15c24e80-6ab2-11ea-84eb-0072d667889c.png)

After that my go.mod file looks like this:
![Screen Shot 2020-03-20 at 1 44 33 PM](https://user-images.githubusercontent.com/29229656/77161425-528e4580-6ab2-11ea-8f70-0404e0389228.png)

I really hope that you did not remove the Postgres database support from the beego-orm-adapter, since our application runs on Postgres:

![Screen Shot 2020-03-20 at 4 05 21 PM](https://user-images.githubusercontent.com/29229656/77171252-d6e9c400-6ac4-11ea-947c-fffaeb8b3bd5.png)

![Screen Shot 2020-03-20 at 4 03 47 PM](https://user-images.githubusercontent.com/29229656/77171279-df41ff00-6ac4-11ea-8b7c-ff2cb5854a25.png)

One more question: Is it possible to use an existing database for the table "casbin_rule" and not create a new one instead? And how can I turn off auto-migrations when run initializing the beego-orm-adapter?

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
get `go get github.com/lib/pq` then add import.

**Comment by nodece** [comment]
checkout test: https://github.com/casbin/beego-orm-adapter/blob/master/adapter_test.go

**Comment by nodece** [comment]
I suggest backup your table then import them into `casbin_rule`.

**Comment by hsluoyz** [comment]
> get `go get github.com/lib/pq` then add import.

This is why I suggest adding a PostgreSQL example. It's not very easy to guess without asking the author.

**Comment by MaksNech** [comment]
@hsluoyz @nodece  Sorry, but it still doesn't install correctly through Go modules:
Catch the same message:
![Screen Shot 2020-03-20 at 6 50 14 PM](https://user-images.githubusercontent.com/29229656/77187397-158b7880-6add-11ea-8d1b-0d0e90347f5c.png)

My go.mod file still without beego-orm-adapter/v2:

![Screen Shot 2020-03-20 at 6 55 03 PM](https://user-images.githubusercontent.com/29229656/77187796-afebbc00-6add-11ea-967b-ed863bb5c253.png)

With  Regardness.

**Comment by nodece** [comment]
@hsluoyz Could you release a new tag?

**Comment by hsluoyz** [comment]
Released: https://github.com/casbin/beego-orm-adapter/releases/tag/v2.0.1

**Comment by nodece** [comment]
@MaksNech It is working!

**Comment by MaksNech** [comment]
@hsluoyz @nodece Hi colleagues, Yeah it's working. Thank you very much! It's great. 
I would like to express my desire as a software developer. Sometimes it’s not very convenient to create a separate table under Casbin, but you need to use the one that is. If you use an existing table, when you call the "NewAdapter()" -> "a.Open()" -> "a.createTable()" methods, automatic migrations starts. 

![Screen Shot 2020-03-21 at 10 39 04 PM](https://user-images.githubusercontent.com/29229656/77236176-d46e9380-6bc4-11ea-8374-6f55c5246c7b.png)
![Screen Shot 2020-03-21 at 10 22 50 PM](https://user-images.githubusercontent.com/29229656/77235912-89538100-6bc2-11ea-9525-60cf36e80368.png)
![Screen Shot 2020-03-21 at 10 24 00 PM](https://user-images.githubusercontent.com/29229656/77235933-b142e480-6bc2-11ea-82bd-02f33780bffe.png)
![Screen Shot 2020-03-21 at 10 24 00 PM](https://user-images.githubusercontent.com/29229656/77235946-c455b480-6bc2-11ea-9ec0-346a057d5d5d.png)
![Screen Shot 2020-03-21 at 10 34 53 PM](https://user-images.githubusercontent.com/29229656/77236120-3c70aa00-6bc4-11ea-84b4-d13548c994dc.png)

As you can see in the screenshots, I commented out these methods so that they are not called. Earlier, I created the “casbin_rule” table in my database with the corresponding fields that you declared in the “CasbinRule” structure. This solved the problem of auto-migration.

This is not very convenient when CI / CD is configured on the server. It would be nice if, for example, you added a boolean flag to the "NewAdapter()" method, which would prohibit the creation of a new table and the launch of the "a.createTable()" method in the "orm_adapter.go" file. Best wishes.

**Comment by hsluoyz** [comment]
@MaksNech can you make a PR about it?
